import np as numpy
# NumPy: Thinking in Arrays

In [57]:
import numpy as np
np.array([6, 28, 496, 8182])


array([   6,   28,  496, 8182])

NumPy provides a number of ways to create arrays in addition to the normal `array()` fn.
- `arange()`
- `zeroes()`
- `ones()`
- `empty()`

In [58]:
np.arange(6)



array([0, 1, 2, 3, 4, 5])

In [59]:
np.zeros(4)

array([0., 0., 0., 0.])

In [60]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [61]:
np.empty(4)

array([0., 0., 0., 0.])

In [62]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [63]:
np.logspace(2,-1,4)

array([100. ,  10. ,   1. ,   0.1])

| Attribute  | Description  
|---|---|
|  `data` | Buffer to the raw array data  |  
|  `dtype` |  type info |  
|  `base` | pointer to another array where data is stored, none if data is stored here |
| `ndim` | number of dimesions |
|`shape` | tuple of integers that represent the rank along each dimension, has length of `ndim`|
|`size` | total num of elements, eql to product of aall elements of shape |
`itemsize` | num of bytes per element |
| `nbytes` | tot num of bytes, eql to `szie` times `itemsize`|
`strides` | num of bytes between the i'th element of each axis and the i +1th element along the same axis|
| `flags` | low lvl memory layout info| 



A common method of reshaping an existing array is to assign a new tuple of integers to the shape attribute

In [64]:
a = np.arange(4)
a.shape =(2,2)
a

array([[0, 1],
       [2, 3]])

In [65]:
np.array(['i will have length six', 'and so will i'], dtype='S7')


array([b'i will ', b'and so '], dtype='|S7')

### Slicing and Views


In [66]:
a = np.arange(8)
a[::-1]


array([7, 6, 5, 4, 3, 2, 1, 0])

In [67]:
a[2:6]

array([2, 3, 4, 5])

In [68]:
a[1::3]

array([1, 4, 7])

what's different about slicing here is that NumPy arrays are N-dim, so you can slice along any and all axes, in Python, if you want to slice along multiple axes, say in a list of list, you have to slice the inner list for every element in the outer list:

In [69]:
outer = [...]
selection = [inner[a:b:c] for inner in outer [x:y:z]]

NameError: name 'x' is not defined

the number of nested `for` loops that is needed to slice lists of list is the number of dim minus one. In NumPy, rather than indexing by a slice, you can index by a tuple of slices which each have their own dim

In [ ]:
outer =np.array([...])
selection = outer[x:y:z, a:b:c]

- the `for` loops implied by multidimensionalslicing are all implicitly handled by NumPy at the C layer, making executing complex slices much faster than writing the `for` loops explicitly in python
- only useful if array has dimensionality greater than 1
- if axis is left out of multidemsional slice, all elements along that dimension are included
- note that rows come before columns in NumPy

create a multidimensional array:

In [ ]:
a=np.arange(16)
a.shape=(4,4)
a[::2,1::2]


array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a[2::-1,:3]

array([[ 8,  9, 10],
       [ 4,  5,  6],
       [ 0,  1,  2]])

### Arithmetic and Broadcasting
- performs math in an *element-wise* fashion
- blah blah performance

Here is the numerical derivative $\frac{dy}{dx}$ :

`(y[1:]-y[:-1])/(x[1:]-x[:-1])`

This method treats pts in `x` and `y` as bin boundaries and returns ther derivative for the center points `((x[1:] + x[:-1])/2)`. This results in length of result is 1 shorther than the lengths of an original array.

If you want to instead treat the pts of the array as the center points with proper upper and lower bound handling so the result has the same length as the original arrays, use NumPy's `gradient()` fn:

`np.gradient(y)/np.gradient(x)`